apiVersion: 1

datasources:
  - name: clickhouse-x-auth
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
      useYandexCloudAuthorization: true
      xHeaderKey: ""
      xHeaderUser: "default"
